# Generated by Django 5.1.4 on 2025-01-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_mymodel_qr_genration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_genration',
            name='image',
            field=models.ImageField(upload_to='qr/'),
        ),
        migrations.AlterField(
            model_name='qr_genration',
            name='link',
            field=models.URLField(),
        ),
    ]
