# Generated by Django 5.1.4 on 2025-01-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='url_shortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('shorten_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='URL',
        ),
    ]
