# Generated by Django 5.1.4 on 2025-01-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_url_shortener_delete_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='link_detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('malcious', models.CharField(max_length=50)),
                ('suspicious', models.CharField(max_length=50)),
                ('undetected', models.CharField(max_length=50)),
                ('harmless', models.CharField(max_length=50)),
                ('timeout', models.CharField(max_length=50)),
            ],
        ),
    ]
