# Generated by Django 5.1.4 on 2025-01-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_link_detection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link_detection',
            old_name='malcious',
            new_name='malicious',
        ),
    ]
